name: VirtualMachineMonitoringSystemFrontend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build_and_push_docker_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: docker build . --file Dockerfile --tag ${DOCKER_USERNAME}/virtualmachinemonitoringsystemfrontend:${{github.sha}}
    - name: Docker Login
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      uses: docker/login-action@v2.0.0
      with: 
        username: ${DOCKER_USERNAME}
        password: ${DOCKER_TOKEN}
    - name: Push Docker Image
      env: 
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_TOKEN: ${{secrets.DOCKER_TOKEN}}
      run: docker push ${DOCKER_USERNAME}/virtualmachinemonitoringsystemfrontend:${{github.sha}}
    
